name: Build-gcc

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  build-gcc:
    runs-on: windows-latest

    steps:
    - name: Install build tools
      run: |
        choco upgrade all
        choco install python
        choco install strawberryperl
        choco install cygwin
        choco install make
      shell: pwsh

    - name: Build GCC
      run: |
        git pull

        mkdir build
        mkdir GCC

        cd build

        bash ./../gcc/configure --prefix=../GCC --enable-languages=c,c++
        make

        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Building gcc" -a
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
