name: Pull-gcc

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  pull-gcc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull
      run: |
        rm -rf ./gcc
        git clone git://gcc.gnu.org/git/gcc.git gcc

    - name: Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Pulling gcc" -a
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
